# Use an official Python runtime as a parent image
FROM mcr.microsoft.com/playwright/python:v1.33.0-jammy

# Set the working directory to /app
WORKDIR /app

# Copy requirements.txt to the working directory
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Set the default command to run the Playwright Python script
#CMD ["python", "main.py"]
RUN ["pytest", "main.py"]