name: Docker Image CI

on:
  schedule:
    - cron: "0 20 * * *"
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  
  workflow_dispatch:
    inputs:
      actionsBranch:
        description: 'Actions branch, tag or SHA to checkout'
        required: true
        default: master
      environment:
        description: 'Environment for deployment'
        required: true
        type: choice
        options:
        - testing
        - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
         python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              #pip install ruff pytest
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
              pytest unit_testing/web_services_tests.py
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run:  docker build . -t web-service-voating--app
      - uses: docker/build-push-action@v2
        with:
          push: false
    
      - name: Run Docker container
        run: docker run -d -p 5002:5002 web-service-voating--app
