name: Docker Image CI

on:
  schedule:
    - cron: "0 20 * * *"
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  
  workflow_dispatch:
    inputs:
      actionsBranch:
        description: 'Actions branch, tag or SHA to checkout'
        required: true
        default: master
      environment:
        description: 'Environment for deployment'
        required: true
        type: choice
        options:
        - testing
        - production

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker build . -t python-scrraper-app
     #docker build . --file Dockerfile --tag docker build . -t python-scrraper-app:$(date +%s)
    
    - uses: docker/build-push-action@v2
      with:
        push: false
    
    - uses: addnab/docker-run-action@v3
      with:
       image: python-scrraper-app:$(date +%s)
        options:--rm -it -p 5002:5002
       run: echo "hello world"
